import { FrontendCardData, SectorData, playerColors } from '@/lib/types';

import { FALLBACK_GAME_POSTER } from '@/lib/constants';
import {
  HltbGamesListResponse,
  InstantCardType,
  MainBonusCardType,
  PlayerDetails,
} from './api-types-generated';

export const sectorsData: SectorData[] = [
  {
    id: 1,
    name: 'Площадь Базовая',
    position: { x: 0, y: 0 },
    type: 'start-corner',
    rollType: 'steam',
    gameLengthRanges: { min: 3, max: 22 },
  },
  {
    id: 2,
    name: 'проспект героев ХПГ',
    position: { x: 1, y: 0 },
    type: 'property',
    color: 'brown',
    rollType: 'auc',
  },
  {
    id: 3,
    name: 'улица Трясская',
    position: { x: 2, y: 0 },
    type: 'bonus',
    rollType: 'steam',
    gameLengthRanges: { min: 6, max: 15 },
  },
  {
    id: 4,
    name: 'улица Аукусная',
    position: { x: 3, y: 0 },
    type: 'property',
    color: 'brown',
    rollType: 'auc',
  },
  {
    id: 5,
    name: 'переулок Осудителей',
    position: { x: 4, y: 0 },
    type: 'property',
    color: 'brown',
    rollType: 'auc',
  },
  {
    id: 6,
    name: 'Твичевский вокзал',
    position: { x: 5, y: 0 },
    type: 'railroad',
    rollType: 'steam',
    gameLengthRanges: { min: 6, max: 19 },
    color: 'gray',
  },
  {
    id: 7,
    name: 'улица 1984 года',
    position: { x: 6, y: 0 },
    type: 'property',
    color: 'lightblue',
    rollType: 'auc',
  },
  {
    id: 8,
    name: 'Рандомный бульвар',
    position: { x: 7, y: 0 },
    type: 'bonus',
    rollType: 'steam',
    gameLengthRanges: { min: 3, max: 12 },
  },
  {
    id: 9,
    name: 'улица Пушкина',
    position: { x: 8, y: 0 },
    type: 'property',
    color: 'lightblue',
    rollType: 'auc',
  },
  {
    id: 10,
    name: 'Чатовское шоссе',
    position: { x: 9, y: 0 },
    type: 'property',
    color: 'lightblue',
    rollType: 'auc',
  },
  {
    id: 11,
    name: 'Тюрьма «Азкабан»',
    position: { x: 10, y: 0 },
    type: 'prison',
    rollType: 'steam',
    gameLengthRanges: { min: 0, max: 300 },
  },
  {
    id: 12,
    name: 'улица Гачино',
    position: { x: 10, y: 1 },
    type: 'property',
    color: 'pink',
    rollType: 'auc',
  },
  {
    id: 13,
    name: 'улица Стимовская',
    position: { x: 10, y: 2 },
    type: 'bonus',
    rollType: 'steam',
    gameLengthRanges: { min: 6, max: 15 },
  },
  {
    id: 14,
    name: 'улица 60-летия Аука',
    position: { x: 10, y: 3 },
    type: 'property',
    color: 'pink',
    rollType: 'auc',
  },
  {
    id: 15,
    name: 'Шейховый проезд',
    position: { x: 10, y: 4 },
    type: 'property',
    color: 'pink',
    rollType: 'auc',
  },
  {
    id: 16,
    name: 'Вкплеевский вокзал',
    position: { x: 10, y: 5 },
    type: 'railroad',
    rollType: 'steam',
    gameLengthRanges: { min: 3, max: 16 },
    color: 'gray',
  },
  {
    id: 17,
    name: 'улица Платно',
    position: { x: 10, y: 6 },
    type: 'property',
    color: 'orange',
    rollType: 'auc',
  },
  {
    id: 18,
    name: 'улица Бесплатно',
    position: { x: 10, y: 7 },
    type: 'bonus',
    rollType: 'steam',
    gameLengthRanges: { min: 3, max: 12 },
  },
  {
    id: 19,
    name: 'Дроповый переулок',
    position: { x: 10, y: 8 },
    type: 'property',
    color: 'orange',
    rollType: 'auc',
  },
  {
    id: 20,
    name: 'проспект Советов',
    position: { x: 10, y: 9 },
    type: 'property',
    color: 'orange',
    rollType: 'auc',
  },
  {
    id: 21,
    name: 'Парковка «Ноу Каппа»',
    position: { x: 10, y: 10 },
    type: 'parking',
    rollType: 'steam',
    gameLengthRanges: { min: 3, max: 22 },
  },
  {
    id: 22,
    name: 'улица героев Рунета',
    position: { x: 9, y: 10 },
    type: 'property',
    color: 'red',
    rollType: 'auc',
  },
  {
    id: 23,
    name: 'аллея Мошны',
    position: { x: 8, y: 10 },
    type: 'bonus',
    rollType: 'steam',
    gameLengthRanges: { min: 6, max: 15 },
  },
  {
    id: 24,
    name: 'авеню Уравнителей',
    position: { x: 7, y: 10 },
    type: 'property',
    color: 'red',
    rollType: 'auc',
  },
  {
    id: 25,
    name: 'улица 1080 павших',
    position: { x: 6, y: 10 },
    type: 'property',
    color: 'red',
    rollType: 'auc',
  },
  {
    id: 26,
    name: 'Киковский вокзал',
    position: { x: 5, y: 10 },
    type: 'railroad',
    rollType: 'steam',
    gameLengthRanges: { min: 6, max: 19 },
    color: 'gray',
  },
  {
    id: 27,
    name: 'улица Паст',
    position: { x: 4, y: 10 },
    type: 'property',
    color: 'yellow',
    rollType: 'auc',
  },
  {
    id: 28,
    name: 'улица Скамино',
    position: { x: 3, y: 10 },
    type: 'property',
    color: 'yellow',
    rollType: 'auc',
  },
  {
    id: 29,
    name: 'улица им. Патрего',
    position: { x: 2, y: 10 },
    type: 'bonus',
    rollType: 'steam',
    gameLengthRanges: { min: 3, max: 12 },
  },
  {
    id: 30,
    name: 'Аниме проспект',
    position: { x: 1, y: 10 },
    type: 'property',
    color: 'yellow',
    rollType: 'auc',
  },
  {
    id: 31,
    name: 'Тюрьма «Шоушенк»',
    position: { x: 0, y: 10 },
    type: 'prison',
    rollType: 'steam',
    gameLengthRanges: { min: 0, max: 300 },
  },
  {
    id: 32,
    name: 'Скуфский бульвар',
    position: { x: 0, y: 9 },
    type: 'property',
    color: 'green',
    rollType: 'auc',
  },
  {
    id: 33,
    name: 'квартал Красных фонарей',
    position: { x: 0, y: 8 },
    type: 'property',
    color: 'green',
    rollType: 'auc',
  },
  {
    id: 34,
    name: 'переулок Терпения',
    position: { x: 0, y: 7 },
    type: 'bonus',
    rollType: 'steam',
    gameLengthRanges: { min: 6, max: 15 },
  },
  {
    id: 35,
    name: 'улица Перекатная',
    position: { x: 0, y: 6 },
    type: 'property',
    color: 'green',
    rollType: 'auc',
  },
  {
    id: 36,
    name: 'Гудгеймовский вокзал',
    position: { x: 0, y: 5 },
    type: 'railroad',
    rollType: 'steam',
    gameLengthRanges: { min: 3, max: 16 },
    color: 'gray',
  },
  {
    id: 37,
    name: 'аллея Стримхат',
    position: { x: 0, y: 4 },
    type: 'property',
    color: 'blue',
    rollType: 'auc',
  },
  {
    id: 38,
    name: 'улица Ластецкая',
    position: { x: 0, y: 3 },
    type: 'property',
    color: 'blue',
    rollType: 'auc',
  },
  {
    id: 39,
    name: 'улица Мегаластецкая',
    position: { x: 0, y: 2 },
    type: 'bonus',
    rollType: 'steam',
    gameLengthRanges: { min: 3, max: 12 },
  },
  {
    id: 40,
    name: 'улица Ультраластецкая',
    position: { x: 0, y: 1 },
    type: 'property',
    color: 'blue',
    rollType: 'auc',
  },
];

// const streetNames = new Set();
// for (const sector of sectorsData) {
//   if (streetNames.has(sector.name)) {
//     console.log('duplicate: ', sector.name, sector.id);
//   }
//   streetNames.add(sector.name);
// }

export const SectorsById: Record<number, SectorData> = Object.fromEntries(
  sectorsData.map(sector => [sector.id, sector])
);

export const PrisonSectors = sectorsData.filter(s => s.type === 'prison');

export const playersData: PlayerDetails[] = [
  {
    id: 1,
    username: 'Praden',
    first_name: 'Денис',
    is_online: true,
    sector_id: 11,
    avatar_link: 'https://github.com/shadcn.png',
    url_handle: 'praden',

    current_game: 'Gothic',
    current_game_updated_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 86976,
    current_game_cover: FALLBACK_GAME_POSTER,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_auc_total_sum: null,
    pointauc_token: 'abc',

    main_platform: 'twitch',
    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 0,
    maps_completed: 0,
    color: playerColors.red,
    model_name: '/cars/race-future1.glb',
    building_upgrade_bonus: 0,
    game_difficulty_level: 0,

    games: [
      {
        id: 1,
        player_id: 1,
        sector_id: 38,
        created_at: Math.ceil(Date.now() / 1000),
        length: '2-5',
        title: 'Haste',
        duration: 0,
        rating: 5,
        review: `123 а тут иконка внутри спойлера [spoiler]спойлер и иконка [7tv]01F753XAGR000F17N8G1S0769B[/7tv][/spoiler] а тут [spoiler]длинный спойлер во всю строку для проверки в отзывах продолжается продолжается продолжается продолжается [/spoiler]`,
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/123456789',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 1,
      },
      {
        id: 2,
        player_id: 1,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '25+',
        title: 'Haste',
        duration: 7200,
        rating: 8,
        review: 'Очень интересная игра, много стратегий!',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/987654321',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
      {
        id: 3,
        player_id: 1,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '20-25',
        title: 'Haste',
        duration: 5400,
        rating: 7,
        review: 'Хорошая игра, но есть недочеты.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/1122334455',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
      {
        id: 4,
        player_id: 1,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '15-20',
        title: 'Haste',
        duration: 4800,
        rating: 6,
        review: 'Неплохая игра, но не моя любимая.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/5566778899',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
      {
        id: 5,
        player_id: 1,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '10-15',
        title: 'Haste',
        duration: 3000,
        rating: 4,
        review: 'Средняя игра, есть лучше.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/9988776655',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
      {
        id: 6,
        player_id: 1,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '5-10',
        title: 'Haste',
        duration: 1800,
        rating: 3,
        review: 'Не очень понравилась, слишком простая.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/2233445566',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
      {
        id: 7,
        player_id: 1,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '2-5',
        title: 'Haste',
        duration: 1200,
        rating: 2,
        review: 'Не понравилась, слишком скучная.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/6677889900',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
      {
        id: 111,
        player_id: 1,
        sector_id: 4,
        created_at: Math.ceil(Date.now() / 1000),
        length: '2-5',
        title: 'Haste',
        duration: 1200,
        rating: 2,
        review: 'Не понравилась, слишком скучная.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/6677889900',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
      {
        id: 112,
        player_id: 1,
        sector_id: 2,
        created_at: Math.ceil(Date.now() / 1000),
        length: '2-5',
        title: 'Haste',
        duration: 1200,
        rating: 2,
        review: 'Не понравилась, слишком скучная.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/6677889900',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
    ],
    bonus_cards: [
      {
        bonus_type: 'game-help-allowed',
        received_at: Math.ceil(Date.now() / 1000),
        received_on_sector: 5,
        cooldown_turns_left: 0,
      },
      {
        bonus_type: 'choose-1-die',
        received_at: Math.ceil(Date.now() / 1000),
        received_on_sector: 5,
        cooldown_turns_left: 2,
      },
      {
        bonus_type: 'adjust-roll-by1',
        received_at: Math.ceil(Date.now() / 1000),
        received_on_sector: 5,
        cooldown_turns_left: 1,
      },
    ],
  },
  {
    id: 2,
    sector_id: 11,
    username: 'Player-2',
    first_name: 'Илья',
    is_online: false,
    avatar_link: 'https://github.com/shadcn.png',
    url_handle: 'player-2',

    current_game: 'Gothic',
    current_game_updated_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_game_cover: FALLBACK_GAME_POSTER,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_auc_total_sum: null,
    pointauc_token: 'abc',
    color: playerColors.orange,
    model_name: '/cars/race-future1.glb',

    main_platform: 'twitch',
    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    maps_completed: 0,
    building_upgrade_bonus: 0,
    game_difficulty_level: 0,

    total_score: 5000,
    games: [
      {
        id: 9,
        player_id: 2,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '25+',
        title: 'Haste',
        duration: 7200,
        rating: 9,
        review: 'Прекрасная игра, очень понравилась!',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/123456789',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
      {
        id: 10,
        player_id: 2,
        sector_id: 2,
        created_at: Math.ceil(Date.now() / 1000),
        length: '15-20',
        title: 'Haste',
        duration: 5400,
        rating: 6,
        review: 'Неплохая игра, но есть недочеты.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/987654321',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 2,
      },
      {
        id: 11,
        player_id: 2,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '25+',
        title: 'Haste',
        duration: 6000,
        rating: 8,
        review: 'Очень интересная игра, много стратегий!',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/1122334455',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
      {
        id: 12,
        player_id: 2,
        sector_id: 4,
        created_at: Math.ceil(Date.now() / 1000),
        length: '20-25',
        title: 'Haste',
        duration: 4800,
        rating: 7,
        review: 'Хорошая игра, но есть недочеты.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/5566778899',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 4,
      },
      {
        id: 13,
        player_id: 2,
        sector_id: 2,
        created_at: Math.ceil(Date.now() / 1000),
        length: '15-20',
        title: 'Miraculous: Paris Under Siege (2024)',
        duration: 3600,
        rating: 5,
        review:
          'добротная игрушка, но есть пару недочетов: небольшое однообразие + камера из сериала школа, а так вполне неплохо! добротная игрушка, но есть пару недочетов: небольшое однообразие + камера из сериала школа, а так вполне неплохо! добротная игрушка, но есть пару недочетов: небольшое однообразие + камера из сериала школа, а так вполне неплохо!',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/9988776655',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 2,
      },
      {
        id: 14,
        player_id: 2,
        sector_id: 4,
        created_at: Math.ceil(Date.now() / 1000),
        length: '10-15',
        title: 'Haste',
        duration: 2400,
        rating: 4,
        review: 'Средняя игра, есть лучше.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/2233445566',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 4,
      },
      {
        id: 15,
        player_id: 2,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '5-10',
        title: 'Haste',
        duration: 1200,
        rating: 3,
        review: 'Не очень понравилась, слишком простая.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/6677889900',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
      {
        id: 16,
        player_id: 2,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '2-5',
        title: 'Haste',
        duration: 600,
        rating: 2,
        review: 'Не понравилась, слишком скучная.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/1234567890',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
      {
        id: 17,
        player_id: 2,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '',
        title: 'Haste',
        duration: null,
        rating: 1,
        review: 'Не смог пройти, игра не зашла.',
        status: 'drop',
        vod_links: null,
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
    ],
    bonus_cards: [
      {
        bonus_type: 'adjust-roll-by1',
        received_at: Math.ceil(Date.now() / 1000),
        received_on_sector: 5,
        cooldown_turns_left: 0,
      },
    ],
  },
  {
    id: 3,
    sector_id: 11,
    username: 'Player-3',
    first_name: 'Илья',
    is_online: true,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: 'Gothic',
    current_game_updated_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_game_cover: FALLBACK_GAME_POSTER,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_auc_total_sum: null,
    pointauc_token: 'abc',
    url_handle: 'player-3',
    color: playerColors.brown,
    model_name: '/cars/race-future1.glb',

    main_platform: 'twitch',
    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 1,
    building_upgrade_bonus: 0,
    game_difficulty_level: 0,

    games: [
      {
        id: 18,
        player_id: 3,
        sector_id: 2,
        created_at: Math.ceil(Date.now() / 1000),
        length: '5-10',
        title: 'Haste',
        duration: 2400,
        rating: 4,
        review: 'Средняя игра, есть лучше.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/2233445566',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 2,
      },
      {
        id: 19,
        player_id: 3,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '10-15',
        title: 'Haste',
        duration: 1800,
        rating: 3,
        review: 'Не очень понравилась, слишком простая.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/6677889900',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
    ],
    bonus_cards: [],
  },
  {
    id: 4,
    sector_id: 11,
    username: 'Player-4',
    first_name: 'Илья',
    is_online: false,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: 'Gothic',
    current_game_updated_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_game_cover: FALLBACK_GAME_POSTER,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_auc_total_sum: null,
    pointauc_token: 'abc',
    url_handle: 'player-4',
    color: playerColors.green,
    model_name: '/cars/race-future1.glb',

    main_platform: 'twitch',
    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 2,
    building_upgrade_bonus: 0,
    game_difficulty_level: 0,

    games: [
      {
        id: 20,
        player_id: 4,
        sector_id: 2,
        created_at: Math.ceil(Date.now() / 1000),
        length: '2-5',
        title: 'Haste',
        duration: null,
        rating: 1,
        review: 'Не смог пройти, игра не зашла.',
        status: 'completed',
        vod_links: null,
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 2,
      },
      {
        id: 444,
        player_id: 4,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '20-25',
        title: 'Haste',
        duration: null,
        rating: 1,
        review: 'Не смог пройти, игра не зашла.',
        status: 'completed',
        vod_links: null,
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
      {
        id: 445,
        player_id: 4,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '15-20',
        title: 'Haste',
        duration: null,
        rating: 1,
        review: 'Не смог пройти, игра не зашла.',
        status: 'completed',
        vod_links: null,
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
      {
        id: 446,
        player_id: 4,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '10-15',
        title: 'Haste',
        duration: null,
        rating: 1,
        review: 'Не смог пройти, игра не зашла.',
        status: 'completed',
        vod_links: null,
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
      {
        id: 447,
        player_id: 4,
        sector_id: 4,
        created_at: Math.ceil(Date.now() / 1000),
        length: '2-5',
        title: 'Haste',
        duration: null,
        rating: 1,
        review: 'Не смог пройти, игра не зашла.',
        status: 'completed',
        vod_links: null,
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 4,
      },
    ],
    bonus_cards: [],
  },
  {
    id: 5,
    sector_id: 11,
    username: 'Player-5',
    first_name: 'Илья',
    is_online: false,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: 'Gothic',
    current_game_updated_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_game_cover: FALLBACK_GAME_POSTER,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_auc_total_sum: null,
    pointauc_token: 'abc',
    url_handle: 'player-5',
    color: playerColors.orange,
    model_name: '/cars/race-future1.glb',

    main_platform: 'twitch',
    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 0,
    building_upgrade_bonus: 0,
    game_difficulty_level: 0,

    games: [
      {
        id: 21,
        player_id: 5,
        sector_id: 2,
        created_at: Math.ceil(Date.now() / 1000),
        length: '2-5',
        title: 'Haste',
        duration: 1200,
        rating: 2,
        review: 'Не понравилась, слишком скучная.',
        status: 'completed',
        vod_links:
          'https://www.twitch.tv/videos/1234567890, https://www.twitch.tv/videos/1234567891, https://www.twitch.tv/videos/1234567892',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 2,
      },
    ],
    bonus_cards: [
      {
        bonus_type: 'adjust-roll-by1',
        received_at: Math.ceil(Date.now() / 1000),
        received_on_sector: 5,
        cooldown_turns_left: 0,
      },
    ],
  },
  {
    id: 6,
    sector_id: 11,
    username: 'Player-6',
    first_name: 'Илья',
    is_online: true,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: 'Gothic',
    current_game_updated_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_game_cover: FALLBACK_GAME_POSTER,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_auc_total_sum: null,
    pointauc_token: 'abc',
    url_handle: 'player-6',
    color: playerColors.blue,
    model_name: '/cars/race-future1.glb',

    main_platform: 'twitch',
    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 0,
    building_upgrade_bonus: 0,
    game_difficulty_level: 0,

    games: [
      {
        id: 22,
        player_id: 6,
        sector_id: 4,
        created_at: Math.ceil(Date.now() / 1000),
        length: '10-15',
        title: 'Haste',
        duration: 3600,
        rating: 6,
        review: 'Неплохая игра, но есть недочеты.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/5566778899',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 4,
      },
      {
        id: 99,
        player_id: 6,
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '2-5',
        title: 'Haste',
        duration: 3600,
        rating: 6,
        review: 'Неплохая игра, но есть недочеты.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/5566778899',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 5,
      },
      {
        id: 999,
        player_id: 6,
        sector_id: 2,
        created_at: Math.ceil(Date.now() / 1000),
        length: '15-20',
        title: 'Haste',
        duration: 3600,
        rating: 6,
        review: 'Неплохая игра, но есть недочеты.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/5566778899',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 2,
      },
    ],
    bonus_cards: [
      {
        bonus_type: 'adjust-roll-by1',
        received_at: Math.ceil(Date.now() / 1000),
        received_on_sector: 5,
        cooldown_turns_left: 0,
      },
    ],
  },
  {
    id: 7,
    sector_id: 10,
    username: 'Player-7',
    first_name: 'Илья',
    is_online: true,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: 'Gothic',
    current_game_updated_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_game_cover: FALLBACK_GAME_POSTER,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_auc_total_sum: null,
    pointauc_token: 'abc',
    url_handle: 'player-7',
    color: playerColors.darkBlue,
    model_name: '/cars/race-future1.glb',

    main_platform: 'twitch',
    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 0,
    building_upgrade_bonus: 0,
    game_difficulty_level: 0,

    games: [
      {
        id: 23,
        player_id: 7,
        sector_id: 6,
        created_at: Math.ceil(Date.now() / 1000),
        length: '15-20',
        title: 'Haste',
        duration: 4800,
        rating: 7,
        review: 'Хорошая игра, но есть недочеты.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/9988776655',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 6,
      },
      {
        id: 777,
        player_id: 7,
        sector_id: 16,
        created_at: Math.ceil(Date.now() / 1000),
        length: '15-20',
        title: 'Haste',
        duration: 4800,
        rating: 7,
        review: 'Хорошая игра, но есть недочеты.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/9988776655',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 16,
      },
      {
        id: 778,
        player_id: 7,
        sector_id: 26,
        created_at: Math.ceil(Date.now() / 1000),
        length: '15-20',
        title: 'Haste',
        duration: 4800,
        rating: 7,
        review: 'Хорошая игра, но есть недочеты.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/9988776655',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 7,
      },
      {
        id: 779,
        player_id: 7,
        sector_id: 36,
        created_at: Math.ceil(Date.now() / 1000),
        length: '15-20',
        title: 'Haste',
        duration: 4800,
        rating: 7,
        review: 'Хорошая игра, но есть недочеты.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/9988776655',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 7,
      },
    ],
    bonus_cards: [
      {
        bonus_type: 'adjust-roll-by1',
        received_at: Math.ceil(Date.now() / 1000),
        received_on_sector: 5,
        cooldown_turns_left: 0,
      },
    ],
  },
  {
    id: 8,
    sector_id: 10,
    username: 'Player-8',
    first_name: 'Илья',
    is_online: true,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: null,
    current_game_updated_at: null,
    current_game_cover: null,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_auc_total_sum: null,
    pointauc_token: 'abc',
    url_handle: 'player-8',
    color: playerColors.purple,
    model_name: '/cars/race-future1.glb',

    main_platform: 'vk',
    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 1,
    building_upgrade_bonus: 1,
    game_difficulty_level: 1,

    games: [
      {
        id: 24,
        player_id: 8,
        sector_id: 10,
        created_at: Math.ceil(Date.now() / 1000),
        length: '5-10',
        title: 'Haste',
        duration: 1800,
        rating: 3,
        review: 'Не очень понравилась, слишком простая.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/2233445566',
        cover: FALLBACK_GAME_POSTER,
        length_bonus: 0,
        difficulty_level: 0,
        player_sector_id: 8,
      },
    ],
    bonus_cards: [
      {
        bonus_type: 'adjust-roll-by1',
        received_at: Math.ceil(Date.now() / 1000),
        received_on_sector: 5,
        cooldown_turns_left: 0,
      },
    ],
  },
  {
    id: 9,
    sector_id: 10,
    username: 'Player-9',
    first_name: 'Илья',
    is_online: true,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: null,
    current_game_updated_at: null,
    current_game_cover: null,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_auc_total_sum: null,
    pointauc_token: 'abc',
    url_handle: 'player-8',
    color: playerColors.purple,
    model_name: '/boats/boat-sail-b.glb',

    main_platform: 'kick',
    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 0,
    games: [],
    bonus_cards: [],
    building_upgrade_bonus: 0,
    game_difficulty_level: 0,
  },
  {
    id: 10,
    sector_id: 10,
    username: 'Player-10',
    first_name: 'Илья',
    is_online: true,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: null,
    current_game_updated_at: null,
    current_game_cover: null,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_auc_total_sum: null,
    pointauc_token: 'abc',
    url_handle: 'player-8',
    color: playerColors.purple,
    model_name: '/boats/boat-sail-b.glb',

    main_platform: 'twitch',
    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 0,
    games: [],
    bonus_cards: [],
    building_upgrade_bonus: 0,
    game_difficulty_level: 0,
  },
  {
    id: 11,
    sector_id: 10,
    username: 'Player-11',
    first_name: 'Илья',
    is_online: true,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: null,
    current_game_updated_at: null,
    current_game_cover: null,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_auc_total_sum: null,
    pointauc_token: 'abc',
    url_handle: 'player-8',
    color: playerColors.purple,
    model_name: '/boats/boat-sail-b.glb',

    main_platform: 'twitch',
    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 0,
    games: [],
    bonus_cards: [],
    building_upgrade_bonus: 0,
    game_difficulty_level: 0,
  },
  {
    id: 12,
    sector_id: 10,
    username: 'Player-12',
    first_name: 'Илья',
    is_online: true,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: null,
    current_game_updated_at: null,
    current_game_cover: null,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_auc_total_sum: null,
    pointauc_token: 'abc',
    url_handle: 'player-8',
    color: playerColors.purple,
    model_name: '/boats/boat-sail-b.glb',

    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 0,
    games: [],
    bonus_cards: [],
    building_upgrade_bonus: 0,
    game_difficulty_level: 0,
  },
];

export const frontendCardsData: Record<MainBonusCardType, FrontendCardData> = {
  'adjust-roll-by1': {
    name: 'Подкрутка',
    picture: `${import.meta.env.BASE_URL}assets/cards/adjust-roll-by1.png`,
    description:
      'Выбрать: добавить или убавить 1 к результату броска кубиков. (Используется перед началом движения.)',
  },
  'choose-1-die': {
    name: 'Теорема Эскобара',
    picture: `${import.meta.env.BASE_URL}assets/cards/choose-1-die.png`,
    description:
      'Выбрать только один из брошенных кубиков и сходить на данное значение. (Используется перед началом движения.)',
  },
  'reroll-game': {
    name: 'Видеоигровой журналист',
    picture: `${import.meta.env.BASE_URL}assets/cards/reroll-game.png`,
    description:
      'Реролл игры из стима ИЛИ реролл игры аукциона. (Игру с аукциона необходимо играть качественно 3ч, реролл происходит из тех же вариантов аукциона.)',
  },
  'skip-prison-day': {
    name: 'Прилежное поведение',
    picture: `${import.meta.env.BASE_URL}assets/cards/skip-prison-day.png`,
    description: 'Позволяет покинуть тюрьму. (Используется до ролла игры в тюрьме.)',
  },
  'evade-street-tax': {
    name: 'Сквоттер',
    picture: `${import.meta.env.BASE_URL}assets/cards/evade-street-tax.png`,
    description:
      'Отсутствие аренды на секторе с чужими постройками. (Игрок не теряет очки, соперники не приобретают очки.)',
  },
  'evade-map-tax': {
    name: 'Уклонение',
    picture: `${import.meta.env.BASE_URL}assets/cards/evade-map-tax.png`,
    description: 'Отсутствие налога за круг.',
  },
  'game-help-allowed': {
    name: 'Лицензия на свинство',
    picture: `${import.meta.env.BASE_URL}assets/cards/game-help-allowed.png`,
    description:
      'Во время прохождения игры разрешается просматривать спидраны, видеопрохождения и любые подсказки чата. В случае реролла карточка продолжает работать на секторе. (Не разрешает скипать диалоги и катсцены.)',
  },
};

export const frontendInstantCardsData: Record<InstantCardType, FrontendCardData> = {
  'receive-1-percent-from-all': {
    name: 'Сюрприз',
    picture: `${import.meta.env.BASE_URL}assets/cards/receive-1-percent-from-all.png`,
    description:
      'В честь вашего дня рождения все другие игроки перечисляют вам очки (1*{X} от каждого).',
  },
  'receive-scores-for-place': {
    name: 'Выбыл, говорите?',
    picture: `${import.meta.env.BASE_URL}assets/cards/receive-scores-for-place.png`,
    description:
      'Получите очки, равные вашему месту в таблице (место * (1+{X})). В перый игровой день, пока места не распределены - получите 5 очков.',
  },
  'receive-5-percent-or-reroll': {
    name: 'Тогда бесплатный тостер',
    picture: `${import.meta.env.BASE_URL}assets/cards/receive-5-percent-or-reroll.png`,
    description:
      'Если вы находитесь на одном из трех последних мест, получите 8*{X} очков, в противном случае - потеряйте 4*{X} очка. В перый игровой день, пока места не распределены - получите 5 очков.',
  },
  // 'receive-3-percent': {
  //   name: 'Деньги то, видит Бог, небольшие',
  //   picture: `${import.meta.env.BASE_URL}assets/cards/receive-3-percent.png`,
  //   description: 'Получите 4 очков.',
  // },
  'leaders-lose-percents': {
    name: 'А вот это явно не моя проблема',
    picture: `${import.meta.env.BASE_URL}assets/cards/leaders-lose-percents.png`,
    description:
      'Первые три места в таблице лидеров теряют 6*{X}, 5*{X}, 4*{X} очков. В перый игровой день, пока места не распределены - получите 5 очков.',
  },
  'receive-1-percent-plus-20': {
    name: 'Просто мы нашли резинку',
    picture: `${import.meta.env.BASE_URL}assets/cards/receive-1-percent-plus-20.png`,
    description: 'Получите 9*{X} очков.',
  },
  'lose-2-percents': {
    name: 'Плата?',
    picture: `${import.meta.env.BASE_URL}assets/cards/lose-2-percents.png`,
    description: 'Потеряйте 4*{X} очков.',
  },
  reroll: {
    name: 'Вернуться к исходной стадии',
    picture: `${import.meta.env.BASE_URL}assets/cards/reroll.png`,
    description: 'Реролл этого колеса.',
  },
  'reroll-and-roll': {
    name: 'Процесс стабилизируется',
    picture: `${import.meta.env.BASE_URL}assets/cards/reroll-and-roll.png`,
    description: 'Реролл этого колеса, плюс один дополнительный ролл.',
    disabled: true,
  },
  'lose-card-or-3-percent': {
    name: 'Просто не повезло',
    picture: `${import.meta.env.BASE_URL}assets/cards/lose-card-or-3-percent.png`,
    description: 'Игрок теряет случайную карточку; если карточек нет, потеря 6*{X} очков.',
  },
  'upgrade-next-building': {
    name: 'Он собирает установку',
    picture: `${import.meta.env.BASE_URL}assets/cards/upgrade-next-building.png`,
    description: 'Плюс один тир следующего здания.',
  },
  'downgrade-next-building': {
    name: 'Я не мог просчитаться',
    picture: `${import.meta.env.BASE_URL}assets/cards/downgrade-next-building.png`,
    description: 'Минус один тир следующего здания.',
  },
  'receive-scores-for-active-cards': {
    name: 'Коллекционер',
    description:
      'Получите количество очков, равное количеству ваших карточек умноженному на 1+{X}. Если карточек нет - реролл колеса.',
    picture: `${import.meta.env.BASE_URL}assets/cards/receive-scores-for-active-cards.png`,
  },
  'decrease-difficulty': {
    name: 'Очки ИЗИ',
    description:
      'Уменьшает сложность подходящей игры на 1. Используется когда начинается новая игра. Пропадает после прохождения или дропа этой игры.',
    picture: `${import.meta.env.BASE_URL}assets/cards/decrease-difficulty.png`,
  },
  'increase-difficulty': {
    name: 'Повязка Рэмбо',
    description:
      'Увеличивает сложность подходящей игры на 1. Используется когда начинается новая игра. Пропадает после прохождения или дропа этой игры.',
    picture: `${import.meta.env.BASE_URL}assets/cards/increase-difficulty.png`,
  },
  'police-search': {
    name: 'Обыск',
    description:
      '50% шанс на перенос случайной карточки в хранилище тюрьмы. Если карточка не потеряна, получите 4*{X} очков',
    picture: `${import.meta.env.BASE_URL}assets/cards/police-search.png`,
  },
  asket: {
    name: 'Аскет',
    description:
      'Если у вас меньше трех карт бонусов, получите 6*{X} очков, в противном случае потеряйте 2*{X} за каждую карту, начиная с третьей (если карт всего 3, штраф за одну и тд).',
    picture: `${import.meta.env.BASE_URL}assets/cards/asket.png`,
  },
};

export const bonusCardsData = {
  ...frontendCardsData,
  ...frontendInstantCardsData,
};

export const mainCardTypes = Object.keys(frontendCardsData) as MainBonusCardType[];

type CreditsItem = {
  name: string;
  action: string;
};

export const CreditsData: CreditsItem[] = [
  { name: 'olegsvs', action: 'фронтенд, бекенд, сервера' },
  { name: 'esouqu', action: 'фронтенд, 3д программирование' },
  { name: 'RomoErectus', action: 'фронтенд, ролл карточек' },
  { name: 'mapcar', action: 'программирование, организация' },
  { name: 'lepayy', action: 'дизайн интерфейсов' },
  { name: 'Рот в говне (huykakoyto)', action: 'арты карточек, логотипов' },
  { name: 'naknagetss (artnaku)', action: 'дизайн 3д карты' },
  { name: 'ksanich', action: 'дизайн 3д моделек, видос' },
  { name: 'Шестиклассник из ФМЛ 239', action: 'аналитика, баланс' },
].sort((a, b) => (a.name.toLowerCase() > b.name.toLowerCase() ? 1 : -1));

export const mockHltbGamesList: HltbGamesListResponse = {
  games: [
    {
      game_id: 133826,
      game_name: 'Tactical Galactical',
      game_name_date: 0,
      game_alias: null,
      game_type: 'game',
      genres: 'Strategy, Turn-Based, 4X, Space, Tactical, Early Access',
      steam_id: 765700,
      description:
        'Tactical Galactical is a turn-based 4X space strategy game. You are the leader of a space empire, and you must build your fleet, research new technologies, and conquer new planets to expand your empire. You can play alone or with friends in co-op mode.',
      game_image: 'https://howlongtobeat.com/games/133826_Tactical_Galactical.jpg',
      comp_lvl_combine: 0,
      comp_lvl_sp: 1,
      comp_lvl_co: 0,
      comp_lvl_mp: 1,
      comp_main: 0,
      comp_plus: 0,
      comp_100: 0,
      comp_all: 0,
      comp_main_count: 0,
      comp_plus_count: 0,
      comp_100_count: 0,
      comp_all_count: 0,
      invested_co: 0,
      invested_mp: 0,
      invested_co_count: 0,
      invested_mp_count: 0,
      count_comp: 0,
      count_speedrun: 0,
      count_backlog: 1,
      count_review: 0,
      review_score: 0,
      count_playing: 0,
      count_retired: 1,
      profile_platform: 'PC',
      profile_popular: 5,
      release_world: 0,
      created_at: 1755445366,
      updated_at: 1755445366,
    },
    {
      game_id: 111055,
      game_name: 'Holonomy',
      game_name_date: 0,
      game_alias: null,
      game_type: 'game',
      game_image: 'https://howlongtobeat.com/games/111055_Holonomy.jpg',
      description:
        'Tactical Galactical is a turn-based 4X space strategy game. You are the leader of a space empire, and you must build your fleet, research new technologies, and conquer new planets to expand your empire. You can play alone or with friends in co-op mode. Tactical Galactical is a turn-based 4X space strategy game. You are the leader of a space empire, and you must build your fleet, research new technologies, and conquer new planets to expand your empire. You can play alone or with friends in co-op mode.',
      comp_lvl_combine: 0,
      comp_lvl_sp: 1,
      comp_lvl_co: 0,
      comp_lvl_mp: 0,
      comp_main: 0,
      comp_plus: 0,
      comp_100: 510,
      comp_all: 510,
      comp_main_count: 0,
      comp_plus_count: 0,
      comp_100_count: 2,
      comp_all_count: 2,
      invested_co: 0,
      invested_mp: 0,
      invested_co_count: 0,
      invested_mp_count: 0,
      count_comp: 2,
      count_speedrun: 0,
      count_backlog: 0,
      count_review: 1,
      review_score: 80,
      count_playing: 0,
      count_retired: 0,
      profile_platform: 'Browser, Linux, Mobile, PC',
      profile_popular: 4,
      release_world: 2022,
      created_at: 1755445366,
      updated_at: 1755445366,
    },
    {
      game_id: 47992,
      game_name: 'The Shrouded Isle',
      game_name_date: 0,
      game_alias: null,
      game_type: 'game',
      game_image: 'https://howlongtobeat.com/games/47992_The_Shrouded_Isle.jpg',
      description:
        'Tactical Galactical is a turn-based 4X space strategy game. You are the leader of a space empire, and you must build your fleet, research new technologies, and conquer new planets to expand your empire. You can play alone or with friends in co-op mode. Tactical Galactical is a turn-based 4X space strategy game. You are the leader of a space empire, and you must build your fleet, research new technologies, and conquer new planets to expand your empire. You can play alone or with friends in co-op mode. Tactical Galactical is a turn-based 4X space strategy game. You are the leader of a space empire, and you must build your fleet, research new technologies, and conquer new planets to expand your empire. You can play alone or with friends in co-op mode.',
      comp_lvl_combine: 0,
      comp_lvl_sp: 1,
      comp_lvl_co: 0,
      comp_lvl_mp: 0,
      comp_main: 14013,
      comp_plus: 29617,
      comp_100: 45981,
      comp_all: 18082,
      comp_main_count: 22,
      comp_plus_count: 12,
      comp_100_count: 3,
      comp_all_count: 37,
      invested_co: 0,
      invested_mp: 0,
      invested_co_count: 0,
      invested_mp_count: 0,
      count_comp: 160,
      count_speedrun: 0,
      count_backlog: 2359,
      count_review: 23,
      review_score: 66,
      count_playing: 14,
      count_retired: 105,
      profile_platform: 'Nintendo Switch, PC',
      profile_popular: 82,
      release_world: 2017,
      created_at: 1755445366,
      updated_at: 1755445366,
    },
    {
      game_id: 79653,
      game_name: 'Cotrio',
      game_name_date: 0,
      game_alias: null,
      game_type: 'game',
      game_image: 'https://howlongtobeat.com/games/79653_Cotrio.jpg',
      description:
        'Tactical Galactical is a turn-based 4X space strategy game. You are the leader of a space empire, and you must build your fleet, research new technologies, and conquer new planets to expand your empire. You can play alone or with friends in co-op mode.',
      comp_lvl_combine: 0,
      comp_lvl_sp: 1,
      comp_lvl_co: 0,
      comp_lvl_mp: 0,
      comp_main: 0,
      comp_plus: 0,
      comp_100: 0,
      comp_all: 0,
      comp_main_count: 0,
      comp_plus_count: 0,
      comp_100_count: 0,
      comp_all_count: 0,
      invested_co: 0,
      invested_mp: 0,
      invested_co_count: 0,
      invested_mp_count: 0,
      count_comp: 0,
      count_speedrun: 0,
      count_backlog: 31,
      count_review: 1,
      review_score: 70,
      count_playing: 0,
      count_retired: 5,
      profile_platform: 'PC',
      profile_popular: 8,
      release_world: 2019,
      created_at: 1755445366,
      updated_at: 1755445366,
    },
    {
      game_id: 41414,
      game_name: 'GrottyScape',
      game_name_date: 0,
      game_alias: null,
      game_type: 'game',
      game_image: 'https://howlongtobeat.com/games/41414_GrottyScape.jpg',
      comp_lvl_combine: 0,
      comp_lvl_sp: 1,
      comp_lvl_co: 0,
      comp_lvl_mp: 0,
      comp_main: 0,
      comp_plus: 0,
      comp_100: 0,
      comp_all: 0,
      comp_main_count: 0,
      comp_plus_count: 0,
      comp_100_count: 0,
      comp_all_count: 0,
      invested_co: 0,
      invested_mp: 0,
      invested_co_count: 0,
      invested_mp_count: 0,
      count_comp: 0,
      count_speedrun: 0,
      count_backlog: 4,
      count_review: 0,
      review_score: 0,
      count_playing: 0,
      count_retired: 0,
      profile_platform: 'PC',
      profile_popular: 0,
      release_world: 2016,
      created_at: 1755445366,
      updated_at: 1755445366,
    },
    {
      game_id: 47140,
      game_name: 'Darkness and Flame: Born of Fire',
      game_name_date: 0,
      game_alias: null,
      game_type: 'game',
      game_image: 'https://howlongtobeat.com/games/47140_Darkness_and_Flame_Born_of_Fire.jpg',
      comp_lvl_combine: 0,
      comp_lvl_sp: 1,
      comp_lvl_co: 0,
      comp_lvl_mp: 0,
      comp_main: 17106,
      comp_plus: 18900,
      comp_100: 19500,
      comp_all: 18195,
      comp_main_count: 1,
      comp_plus_count: 5,
      comp_100_count: 2,
      comp_all_count: 8,
      invested_co: 0,
      invested_mp: 0,
      invested_co_count: 0,
      invested_mp_count: 0,
      count_comp: 14,
      count_speedrun: 0,
      count_backlog: 13,
      count_review: 0,
      review_score: 0,
      count_playing: 0,
      count_retired: 0,
      profile_platform: 'Mobile, PC',
      profile_popular: 0,
      release_world: 2016,
      created_at: 1755445366,
      updated_at: 1755445366,
    },
    {
      game_id: 147068,
      game_name: 'MotoGP 24',
      game_name_date: 0,
      game_alias: null,
      game_type: 'game',
      game_image: 'https://howlongtobeat.com/games/147068_MotoGP_24.jpg',
      comp_lvl_combine: 0,
      comp_lvl_sp: 1,
      comp_lvl_co: 1,
      comp_lvl_mp: 1,
      comp_main: 52449,
      comp_plus: 104160,
      comp_100: 0,
      comp_all: 61282,
      comp_main_count: 4,
      comp_plus_count: 2,
      comp_100_count: 0,
      comp_all_count: 6,
      invested_co: 0,
      invested_mp: 0,
      invested_co_count: 0,
      invested_mp_count: 0,
      count_comp: 10,
      count_speedrun: 0,
      count_backlog: 17,
      count_review: 4,
      review_score: 76,
      count_playing: 2,
      count_retired: 3,
      profile_platform:
        'Nintendo Switch, PC, PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S',
      profile_popular: 12,
      release_world: 2024,
      created_at: 1755445366,
      updated_at: 1755445366,
    },
    {
      game_id: 109326,
      game_name: 'Hot And Lovely 4',
      game_name_date: 0,
      game_alias: null,
      game_type: 'game',
      game_image: 'https://howlongtobeat.com/games/109326_Hot_And_Lovely_4.jpg',
      comp_lvl_combine: 0,
      comp_lvl_sp: 1,
      comp_lvl_co: 0,
      comp_lvl_mp: 0,
      comp_main: 0,
      comp_plus: 0,
      comp_100: 0,
      comp_all: 0,
      comp_main_count: 0,
      comp_plus_count: 0,
      comp_100_count: 0,
      comp_all_count: 0,
      invested_co: 0,
      invested_mp: 0,
      invested_co_count: 0,
      invested_mp_count: 0,
      count_comp: 2,
      count_speedrun: 0,
      count_backlog: 0,
      count_review: 0,
      review_score: 0,
      count_playing: 3,
      count_retired: 0,
      profile_platform: 'PC',
      profile_popular: 6,
      release_world: 2021,
      created_at: 1755445366,
      updated_at: 1755445366,
    },
    {
      game_id: 155645,
      game_name: 'RoadCraft',
      game_name_date: 0,
      game_alias: null,
      game_type: 'game',
      game_image: 'https://howlongtobeat.com/games/155645_RoadCraft.jpg',
      comp_lvl_combine: 0,
      comp_lvl_sp: 1,
      comp_lvl_co: 1,
      comp_lvl_mp: 1,
      comp_main: 183600,
      comp_plus: 183600,
      comp_100: 360000,
      comp_all: 273857,
      comp_main_count: 2,
      comp_plus_count: 1,
      comp_100_count: 4,
      comp_all_count: 7,
      invested_co: 273600,
      invested_mp: 0,
      invested_co_count: 1,
      invested_mp_count: 0,
      count_comp: 10,
      count_speedrun: 0,
      count_backlog: 54,
      count_review: 6,
      review_score: 78,
      count_playing: 54,
      count_retired: 6,
      profile_platform: 'PC, PlayStation 5, Xbox Series X/S',
      profile_popular: 55,
      release_world: 2025,
      created_at: 1755445366,
      updated_at: 1755445366,
    },
    {
      game_id: 37672,
      game_name: 'Gadget Twins',
      game_name_date: 0,
      game_alias: null,
      game_type: 'game',
      game_image: 'https://howlongtobeat.com/games/37672_Gadget_Twins.jpg',
      comp_lvl_combine: 0,
      comp_lvl_sp: 1,
      comp_lvl_co: 1,
      comp_lvl_mp: 1,
      comp_main: 3512,
      comp_plus: 0,
      comp_100: 0,
      comp_all: 3512,
      comp_main_count: 1,
      comp_plus_count: 0,
      comp_100_count: 0,
      comp_all_count: 1,
      invested_co: 0,
      invested_mp: 0,
      invested_co_count: 0,
      invested_mp_count: 0,
      count_comp: 4,
      count_speedrun: 0,
      count_backlog: 11,
      count_review: 4,
      review_score: 40,
      count_playing: 0,
      count_retired: 3,
      profile_platform: 'PC, Sega Mega Drive/Genesis',
      profile_popular: 5,
      release_world: 1992,
      created_at: 1755445366,
      updated_at: 1755445366,
    },
    {
      game_id: 61193,
      game_name: 'Intelligence Trader',
      game_name_date: 0,
      game_alias: null,
      game_type: 'game',
      game_image: 'https://howlongtobeat.com/games/61193_Intelligence_Trader.jpg',
      comp_lvl_combine: 0,
      comp_lvl_sp: 1,
      comp_lvl_co: 0,
      comp_lvl_mp: 0,
      comp_main: 0,
      comp_plus: 0,
      comp_100: 0,
      comp_all: 0,
      comp_main_count: 0,
      comp_plus_count: 0,
      comp_100_count: 0,
      comp_all_count: 0,
      invested_co: 0,
      invested_mp: 0,
      invested_co_count: 0,
      invested_mp_count: 0,
      count_comp: 0,
      count_speedrun: 0,
      count_backlog: 1,
      count_review: 0,
      review_score: 0,
      count_playing: 0,
      count_retired: 2,
      profile_platform: 'Mac, PC',
      profile_popular: 0,
      release_world: 2018,
      created_at: 1755445366,
      updated_at: 1755445366,
    },
    {
      game_id: 38001,
      game_name: 'Battlefield 1',
      game_name_date: 0,
      game_alias: null,
      game_type: 'game',
      game_image: 'https://howlongtobeat.com/games/38001_Battlefield_1.jpg',
      comp_lvl_combine: 0,
      comp_lvl_sp: 1,
      comp_lvl_co: 0,
      comp_lvl_mp: 1,
      comp_main: 24042,
      comp_plus: 35868,
      comp_100: 90860,
      comp_all: 29213,
      comp_main_count: 1108,
      comp_plus_count: 320,
      comp_100_count: 102,
      comp_all_count: 1530,
      invested_co: 261427,
      invested_mp: 304897,
      invested_co_count: 14,
      invested_mp_count: 236,
      count_comp: 4723,
      count_speedrun: 2,
      count_backlog: 3974,
      count_review: 1803,
      review_score: 76,
      count_playing: 101,
      count_retired: 571,
      profile_platform: 'PC, PlayStation 4, Xbox One',
      profile_popular: 462,
      release_world: 2016,
      created_at: 1755445366,
      updated_at: 1755445366,
    },
  ],
};
